version: "3.9"

services:
  casamento:
    build: .
    image: emcasamento
    container_name: emcasamento
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - db_data:/app/prisma

volumes:
  db_data: