version: "3.9"

services:
  casamento:
    build: .
    image: emcasamento
    container_name: emcasamento
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=file:./dev.db
      - SESSION_SECRET=segredo_grande
      - ADMIN_PASSWORD=casamento2026
    volumes:
      - db_data:/app/prisma

volumes:
  db_data: